server:
  port: 8082

spring:
  application:
    name: notification-service
  cloud:
    function:
      definition: handleRegistrationEvent
    stream:
      bindings:
        handleRegistrationEvent-in-0:
          destination: registration-topic
          group: ${spring.application.name}
      kafka:
        binder:
          brokers: localhost:9093

  mail:
    host: smtp.gmail.com
    port: 587
    username: organicbox9810@gmail.com
    password: rcplykljphrxnrwq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
