global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ 'host.docker.internal:8000' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ 'host.docker.internal:9000' ]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  - job_name: 'profile-service'
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]

  - job_name: 'task-service'
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]