server:
  port: 8000

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  #  security:
  #    oauth2:
  #      resource-server:
  #        jwt:
  #          public-key-location: file:public.pem

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2
#            - name: CircuitBreaker
#              args:
#                name: authServiceCircuitBreaker
#                fallbackUri: forward:/fallback/Auth

        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2
#            - name: CircuitBreaker
#              args:
#                name: userServiceCircuitBreaker
#                fallbackUri: forward:/fallback/User

        - id: task-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/tasks/**
          filters:
            - StripPrefix=2
#            - name: CircuitBreaker
#              args:
#                name: taskServiceCircuitBreaker
#                fallbackUri: forward:/fallback/Task

        - id: profile-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/profiles/**
          filters:
            - StripPrefix=2
#            - name: CircuitBreaker
#              args:
#                name: profileServiceCircuitBreaker
#                fallbackUri: forward:/fallback/Profile

    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: api-gateway
  config:
    import: vault://

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #  health:
  #    readiness-state:
  #      enabled: true
  #    liveness-state:
  #      enabled: true
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: ${app.api-prefix}/auth/v3/api-docs
      - name: user-service
        url: ${app.api-prefix}/users/v3/api-docs
      - name: task-service
        url: ${app.api-prefix}/tasks/v3/api-docs
      - name: profile-service
        url: ${app.api-prefix}/profiles/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    enabled: true

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failureRateThreshold: 50
#        slidingWindowSize: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        waitDurationInOpenState: 10s
#        eventConsumerBufferSize: 10
#    instances:
#      authServiceCircuitBreaker:
#        baseConfig: default
#        registerHealthIndicator: true
#      userServiceCircuitBreaker:
#        baseConfig: default
#        registerHealthIndicator: true
#      taskServiceCircuitBreaker:
#        baseConfig: default
#        registerHealthIndicator: true
#      profileServiceCircuitBreaker:
#        baseConfig: default
#        registerHealthIndicator: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

